# Generated by Django 4.2.7 on 2024-03-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment_payment_session_id_payment_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='stripe_product_id'),
        ),
    ]
